"""empty message

Revision ID: 044af0097a2e
Revises: 
Create Date: 2019-05-31 14:36:15.871811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '044af0097a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=True),
    sa.Column('image', postgresql.BYTEA(), nullable=True),
    sa.Column('image_hash', sa.String(length=100), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('record_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_image_hash'), 'object', ['image_hash'], unique=False)
    op.create_index(op.f('ix_object_object_name'), 'object', ['object_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_object_object_name'), table_name='object')
    op.drop_index(op.f('ix_object_image_hash'), table_name='object')
    op.drop_table('object')
    # ### end Alembic commands ###
